#include <stdio.h>
#include <stdlib.h>
#include <rpc/rpc.h>
#include "add.h" // Make sure this header is generated by rpcgen and includes necessary definitions

void add_prog_1(char *host, int x, int y)
{
	CLIENT *clnt;
	int *result_1;
	numbers add_1_arg;

	// Create the client
	clnt = clnt_create(host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}

	// Prepare the arguments
	add_1_arg.a = x;
	add_1_arg.b = y;

	// Call the RPC function
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Result: %d\n", *result_1);
	}

	// Destroy the client handle
	clnt_destroy(clnt);
}

int main(int argc, char *argv[])
{
	char *host;

	// Check the number of arguments
	if (argc < 4)
	{
		printf("usage: %s server_host x y\n", argv[0]);
		exit(1);
	}

	// Get the host and arguments
	host = argv[1];
	add_prog_1(host, atoi(argv[2]), atoi(argv[3]));
	return 0;
}
